### ISSUE TITLE
UserProfileFragmentで一番下のマイクロポストをタップするとクラッシュする

### ISSUE THREAD

**Issue by hanazuki** [pepabo/railstutorial-android#11]
```
08-20 16:53:49.393      972-972/com.pepabo.jodo.jodoroid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 10, size is 10
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at com.pepabo.jodo.jodoroid.MicropostListFragment.onListItemClick(MicropostListFragment.java:67)
            at android.app.ListFragment$2.onItemClick(ListFragment.java:160)
            at android.widget.AdapterView.performItemClick(AdapterView.java:298)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
            at android.widget.AbsListView$1.run(AbsListView.java:3423)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5323)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:974)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:741)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by alotofwe** [comment]
じゃば

**Comment by hanazuki** [comment]
ListViewにヘッダをつけるとonListItemClickでもらえるpositionがひとつずれるらしい

**Comment by ku00** [comment]
:eyes:
